package com.thva.underground.world.biomes.provider;

import com.thva.underground.world.biomes.UGBiomes;

import net.minecraft.world.biome.Biome;
import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;

public class GenLayerUgAddSnow extends GenLayer
{
    public GenLayerUgAddSnow(long seed, GenLayer parent)
    {
        super(seed);
        this.parent = parent;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int areaX, int areaY, int areaWidth, int areaHeight)
    {
    	int fieldId = Biome.getIdForBiome(UGBiomes.UNDERGROUND_FIELD);
    	int plainsId = Biome.getIdForBiome(UGBiomes.UNDERGROUND_PLAINS);
    	int forestId = Biome.getIdForBiome(UGBiomes.UNDERGROUND_FOREST);
    	int fridgeId = Biome.getIdForBiome(UGBiomes.UNDERGROUND_FRIDGE);
    	
        int i = areaX - 1;
        int j = areaY - 1;
        int k = areaWidth + 2;
        int l = areaHeight + 2;
        int[] aint = this.parent.getInts(i, j, k, l);
        int[] aint1 = IntCache.getIntCache(areaWidth * areaHeight);

        for (int i1 = 0; i1 < areaHeight; ++i1)
        {
            for (int j1 = 0; j1 < areaWidth; ++j1)
            {
                int k1 = aint[j1 + 1 + (i1 + 1) * k];
                this.initChunkSeed((long)(j1 + areaX), (long)(i1 + areaY));

                if (k1 == plainsId)
                {
                    aint1[j1 + i1 * areaWidth] = plainsId;
                }
                else
                {
                    int l1 = this.nextInt(6);

                    if (l1 == 0)
                    {
                        l1 = forestId;
                    }
                    else if (l1 <= 1)
                    {
                        l1 = fridgeId;
                    }
                    else
                    {
                        l1 = fieldId;
                    }

                    aint1[j1 + i1 * areaWidth] = l1;
                }
            }
        }

        return aint1;
    }
}